# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        my_provider:
            entity:
                class: WeatherBundle:User
                property : username
    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login

